#端口号
server:
  port: 9090
spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #mail
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  #默认properties
  profiles:
    active: dev
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8
logging:
  file:
    max-size: 10MB
    max-history: 15
  level:
    root: info



